# Generated by Django 5.1.2 on 2024-10-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='room_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='room.room'),
        ),
    ]
